title @s[tag=!reload,scores={lazer=22}] actionbar §aBattery§r 22/22
title @s[tag=!reload,scores={lazer=21}] actionbar §aBattery§r 21/22
title @s[tag=!reload,scores={lazer=20}] actionbar §aBattery§r 20/22
title @s[tag=!reload,scores={lazer=19}] actionbar §aBattery§r 19/22
title @s[tag=!reload,scores={lazer=18}] actionbar §aBattery§r 18/22
title @s[tag=!reload,scores={lazer=17}] actionbar §aBattery§r 17/22
title @s[tag=!reload,scores={lazer=16}] actionbar §aBattery§r 16/22
title @s[tag=!reload,scores={lazer=15}] actionbar §aBattery§r 15/22
title @s[tag=!reload,scores={lazer=14}] actionbar §aBattery§r 14/22
title @s[tag=!reload,scores={lazer=13}] actionbar §aBattery§r 13/22
title @s[tag=!reload,scores={lazer=12}] actionbar §aBattery§r 12/22
title @s[tag=!reload,scores={lazer=11}] actionbar §aBattery§r 11/22
title @s[tag=!reload,scores={lazer=10}] actionbar §aBattery§r 10/22
title @s[tag=!reload,scores={lazer=9}] actionbar §aBattery§r §g9/22
title @s[tag=!reload,scores={lazer=8}] actionbar §aBattery§r §g8/22
title @s[tag=!reload,scores={lazer=7}] actionbar §aBattery§r §g7/22
title @s[tag=!reload,scores={lazer=6}] actionbar §aBattery§r §g6/22
title @s[tag=!reload,scores={lazer=5}] actionbar §aBattery§r §g5/22
title @s[tag=!reload,scores={lazer=4}] actionbar §aBattery§r §g4/22
title @s[tag=!reload,scores={lazer=3}] actionbar §aBattery§r §g3/22
title @s[tag=!reload,scores={lazer=2}] actionbar §aBattery§r §g2/22
title @s[tag=!reload,scores={lazer=1}] actionbar §aBattery§r §g1/22
title @s[tag=!reload,scores={lazer=0}] actionbar §aBattery§r §40/22