execute at @e[type=fire:fire, tag=!sound] run playsound fire.flameth @a[r=28]
tag @e[type=fire:fire, tag=!sound] add sound
execute at @e[family=arbullet, tag=!sound] run playsound fire.r3 @a[r=28]
execute at @e[family=m82bullet, tag=!sound] run playsound fire.m82 @a[r=28]
execute at @e[family=akbullet, tag=!sound] run playsound fire.r1 @a[r=28]
execute at @e[family=srbullet, tag=!sound] run playsound fire.sg @a[r=28]
execute at @e[family=railbullet, tag=!sound] run playsound fire.rail @a[r=28]
execute at @e[family=sgbullet, tag=!sound,c=1] run playsound fire.sg @a[r=28]
execute at @e[family=psbullet, tag=!sound] run playsound fire.hg @a[r=28]
execute at @e[family=gbullet, tag=!sound] run playsound fire.famas @a[r=28]
execute at @e[family=mgbullet, tag=!sound] run playsound fire.mg2 @a[r=28]
execute at @e[family=smgbullet, tag=!sound] run playsound fire.smg @a[r=28]
execute at @e[family=lmgbullet, tag=!sound] run playsound fire.lmg @a[r=28]
execute at @e[family=tankbullet, tag=!sound] run playsound fire.tank @a[r=28]
execute at @e[family=rpgbullet, tag=!sound] run playsound fire.p90 @a[r=28]
tag @e[family=bullet, tag=!sound] add sound