scoreboard players set @s cooldown 20
scoreboard players set @s ak47 30
scoreboard players set @s aug 30
scoreboard players set @s awm 5
scoreboard players set @s lazer 100
scoreboard players set @s m4 30
scoreboard players set @s m16a4 30
scoreboard players set @s scar 30
scoreboard players set @s scarh 20
scoreboard players set @s bar 30
scoreboard players set @s g36 30
scoreboard players set @s hk416 30
scoreboard players set @s m249 100
scoreboard players set @s p90 1
scoreboard players set @s mp5 30
scoreboard players set @s m1911 8
scoreboard players set @s tt33 5
scoreboard players set @s rpg 1
scoreboard players set @s mosin 5
scoreboard players set @s l86 30
scoreboard players set @s an94 30
scoreboard players set @s dp28 30
scoreboard players set @s famas 6
scoreboard players set @s fire 100
scoreboard players set @s glock17 19
scoreboard players set @s glock18 18
scoreboard players set @s k98 5
scoreboard players set @s lewis 50
scoreboard players set @s m9 15
scoreboard players set @s m10 30
scoreboard players set @s m82 10
scoreboard players set @s m110 10
scoreboard players set @s mg42 70
scoreboard players set @s mp40 30
scoreboard players set @s ppsh 30
scoreboard players set @s rpk 100
scoreboard players set @s sar 30
scoreboard players set @s svd 10
scoreboard players set @s thom 30
scoreboard players set @s uzi 30
scoreboard players set @s vz61 20
scoreboard players set @s xm8 30
scoreboard players set @s p38 8
scoreboard players set @s p226 8
scoreboard players set @s t100 30
scoreboard players set @s m416 30
scoreboard players set @s t95 30
scoreboard players set @s ump9 30
scoreboard players set @s mp7 30
scoreboard players set @s ak12 30
scoreboard players set @s t89 30
execute @s[tag=!reload] ~~~ playsound reload.ak47 @s ~~~