replaceitem entity @a slot.enderchest 0 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 1 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 2 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 3 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 4 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 5 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 6 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 7 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 8 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 9 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 10 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 11 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 12 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 13 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 14 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 15 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 16 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 17 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 18 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 19 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 20 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 21 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 22 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 23 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 24 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 25 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a slot.enderchest 26 barrier 64 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
clear @a minecraft:barrier 0 64