scoreboard players remove Battle ALLFlags 1
execute if score Battle ALLFlags matches 10800 run scriptevent gvcv5:BattleNotice "09:00"
execute if score Battle ALLFlags matches 9600 run scriptevent gvcv5:BattleNotice "08:00"
execute if score Battle ALLFlags matches 8400 run scriptevent gvcv5:BattleNotice "07:00"
execute if score Battle ALLFlags matches 7200 run scriptevent gvcv5:BattleNotice "06:00"
execute if score Battle ALLFlags matches 6000 run scriptevent gvcv5:BattleNotice "05:00"
execute if score Battle ALLFlags matches 4800 run scriptevent gvcv5:BattleNotice "04:00"
execute if score Battle ALLFlags matches 3600 run scriptevent gvcv5:BattleNotice "03:00"
execute if score Battle ALLFlags matches 2400 run scriptevent gvcv5:BattleNotice "02:00"
execute if score Battle ALLFlags matches 1200 run scriptevent gvcv5:BattleNotice "01:00"
execute if score Battle ALLFlags matches 600 run scriptevent gvcv5:BattleNotice "00:30"
execute if score Battle ALLFlags matches 300 run scriptevent gvcv5:BattleNotice "00:15"
execute if score Battle ALLFlags matches 200 run scriptevent gvcv5:BattleNotice "00:10"
execute if score Battle ALLFlags matches 100 run scriptevent gvcv5:BattleNotice "00:05"
execute if score Battle ALLFlags matches 80 run scriptevent gvcv5:BattleNotice "00:04"
execute if score Battle ALLFlags matches 60 run scriptevent gvcv5:BattleNotice "00:03"
execute if score Battle ALLFlags matches 40 run scriptevent gvcv5:BattleNotice "00:02"
execute if score Battle ALLFlags matches 20 run scriptevent gvcv5:BattleNotice "00:01"
execute if score Battle ALLFlags matches ..0 run scriptevent gvcv5:lose 
